### ISSUE TITLE
iOS Landscape Orientation

### ISSUE THREAD

**Issue by MHDixon-SWAU** [tomwyr/loader-search-bar#1]
Hello. After testing with an Android emulator, everything seems to work fine. However, after installing on my iPhone 8 (iOS 11), I've encountered a bug when rotating my device into landscape. See the attached picture.
![issue_search_bar](https://user-images.githubusercontent.com/39629740/41053111-555d5bb4-6980-11e8-8b59-0d59281e51d2.jpeg)

**Comment by tomwyr** [comment]
While running on iOS simulator (iPhone X 11.3) bug occurs as well.

**Comment by MHDixon-SWAU** [comment]
Any progress on this and why it might be occurring?

**Comment by tomwyr** [comment]
Hi, thanks for interest. I've been quite busy for last weeks and couldn't look into this. Starting next month, once I get access to physical iPhone device, I'm going to come back into Flutter and fix this issue first.
