### ISSUE TITLE
Feature Request. Searchbar switches back to AppBar after closing.

### ISSUE THREAD

**Issue by JosephDunivan** [tomwyr/loader-search-bar#10]
Would it be better to simply clear the search bar and change the state back to AppBar after clicking on the X icon? Having to click the back button after seems rather clunky and breaks a common UI maxim. I guess the idea is people might want to search for more than one thing per session of SearchBar.

**Comment by JosephDunivan** [comment]
I think for now setting up the user for this expectation would help.  Adding words next to the button would clear up any ambiguity. X should say clear and 🔙 should say cancel next to it. Like a flatbutton.icon with text instead of just an icon.

Alternatively the state of the flat button could be changed such that if the search query is blank, the button would change from “clear” to “cancel”.  This way, one button does both things and the user can click the same button. This would be less clunky and more expected. 

What do you think?

**Comment by tomwyr** [comment]
Second idea seems to be much better - adding hints to buttons would actually mean that they're not self-explanatory. I'd also like to stick more or less with material design principles with this widget.

Over last few days, I've looked at some apps like Twitter/Youtube/Reddit and their approach to "clear button" and decided to adjust it a little bit. Now, _clear button_ will only appear if there's _search query_ provided - this way user won't be confused by two separate buttons, yet he can still cancel search action with one button press.

**Comment by yousifk** [comment]
you can add Autoclose after submitted

**Comment by JosephDunivan** [comment]
> you can add Autoclose after submitted

I don't think users would enjoy that. It's possible they may want to make multiple searches during one search session. If it autoclosed it would add extra steps, by forcing the user to click two buttons every time they want to search.
