### ISSUE TITLE
Creates another search button

### ISSUE THREAD

**Issue by shubham9543** [tomwyr/loader-search-bar#2]
If the default appbar has actions children then on clicking search icon of search bar creates another search icon button.

Suppose my default appbar is
AppBar(
         title: new Text("blabla"),
            actions: <Widget>[      // here created action, and it causes bug
                IconButton(             // item 1
                icon: Icon(Icons.arrow_downward),
                onPressed: null,
              ),
              IconButton(             //item 2
                icon: Icon(Icons.arrow_downward),
                onPressed: null,
              ),
            ],
      )
 as my appbar contains 2 icons button as actions
now as it is used as child for Search bar hence it generates 3 icon button (one for search),

when Search icon is tapped It generates another Search icon  .
if the newly icon is tapped it again generates another icon and the process goes
untill the whole appbar is full of Search icons.

**Comment by tomwyr** [comment]
Fixed in 58f16331f5f78d3ab4818d505c8064f4afa180c7
